# Generated by Django 5.0.6 on 2024-07-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(related_name='capstone_user_set', to='auth.group')),
                ('permissions', models.ManyToManyField(related_name='capstone_user_permissions', to='auth.permission')),
            ],
        ),
    ]
