# Generated by Django 5.0.6 on 2024-07-19 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
