# Generated by Django 5.0.6 on 2024-08-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_remove_quiz_score_userquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquiz',
            name='score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
