# Generated by Django 5.0.6 on 2024-08-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_remove_userquiz_score_quiz_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='isActiveStatus',
            field=models.BooleanField(default=True),
        ),
    ]
