# Generated by Django 5.0.6 on 2024-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_userquiz_isactivestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.AddField(
            model_name='userquiz',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
