# Generated by Django 5.0.6 on 2024-08-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0015_quiz_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
    ]
