# Generated by Django 5.0.6 on 2024-08-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0016_remove_quiz_isactive_remove_quiz_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
