# Generated by Django 5.0.6 on 2024-08-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0017_quiz_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='isActive',
        ),
    ]
